### ISSUE TITLE
Embed H5P content is not showing when outage is active in Moodle 4.1

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-auth_outage#338]
In Moodle 4.1 whne ouatge is active the H5P activities loaded in iframe seem to be broken.

URL example: `/mod/hvp/embed.php?id=123456789`

Error in browser console:

```
Uncaught SyntaxError: Unexpected token '<' (at a0e3ac64b93f8fdde53eb3fe9d87bee8d6fc8777.js:2:1)
h5p.js:56 Unable to find constructor for: H5P.DragQuestion 1.14

jquery.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'on')
    at H5P.on (h5p.js:134:279)
    at HTMLDivElement.<anonymous> (h5p.js:9:97)
    at Function.each (jquery.js:2:2976)
    at S.fn.init.each (jquery.js:2:1454)
    at H5P.init (h5p.js:5:57)
    at HTMLDocument.<anonymous> (h5p.js:170:26)
    at e (jquery.js:2:30005)
    at t (jquery.js:2:30307)
```

**Comment by golenkovm** [comment]
Potentially could be related to #298

**Comment by golenkovm** [comment]
Workaround instructions:
* When outage is active access an H5P activity;
* Open Console tab in browser dev tools, there should be an error like "Uncaught SyntaxError: Unexpected token '<' (at a0e3ac64b93f8fdde53eb3fe9d87bee8d6fc8777.js:2:1)". Please note that js hash "a0e3a...777" could be different;
* That js is a link, copy its url, it should be something like https://your-moodle.net/mod/hvp/proxy_pluginfile.php/1/mod_hvp/cachedassets/a0e3ac64b93f8fdde53eb3fe9d87bee8d6fc8777.js
* Open that URL in a new tab, it should open javascript code, which will have "<!-- Blocked by ip, your ip: x.x.x.x" in its first line;
* Copy that IP address and whitelist it in the outage settings;
* H5P activities should be now displayed correctly in outage mode for your Moodle session. If this needs to be fixed for other users/testers it will most likely require the same steps to be done for each user/tester.
